#!/usr/bin/env bash

source etc/banner
# Banner Add
echo -e "executing: ${LIGHTGREEN} Pubg-paster${NOCOLOR}"
echo "-----------------------"

OUTPUT_DIR="/storage/emulated/0/PUBGPASTER/output"
INPUT_DIR="/storage/emulated/0/PUBGPASTER/INPUT"
LOG_FILE="/storage/emulated/0/PUBGPASTER/log.txt"
PASSWORD="DRAJ"

if [[ ! -d "$OUTPUT_DIR" ]]; then
    mkdir -p "$OUTPUT_DIR"
fi

if [[ ! -d "$INPUT_DIR" ]]; then
    mkdir -p "$INPUT_DIR"
fi

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> "$LOG_FILE"
}

unpacking () {
  log "Starting unpacking: $opt"
  if qemu-i386 $PREFIX/share/quickbms/quickbms -9 -Q etc/tools.bms "$opt" "$OUTPUT_DIR"; then
    echo "Unpacking successful!"
    log "Unpacking successful: $opt"
  else
    echo "Unpacking failed!"
    log "Unpacking failed: $opt"
  fi
}

repacking () {
  log "Starting repacking: $opt"
  if qemu-i386 $PREFIX/share/quickbms/quickbms -9 -w -r -r etc/tools.bms "$opt" "$OUTPUT_DIR"; then
    echo "Repacking successful!"
    log "Repacking successful: $opt"
  else
    echo "Repacking failed!"
    log "Repacking failed: $opt"
  fi
}

search_in_output () {
  read -p "Enter the text to search for: " search_text
  grep -R "$search_text" "$OUTPUT_DIR"
}

function unpack {
  prompt="Please select a file to unpack:"
  options=( $(find "$INPUT_DIR" -name "*.pak") )

  PS3="$prompt "
  select opt in "${options[@]}" "Quit"; do 
    if (( REPLY == 1 + ${#options[@]} )); then
        exit
    elif (( REPLY > 0 && REPLY <= ${#options[@]} )); then
        echo "You picked $opt which is file $REPLY"
        unpacking
        break
    else
        echo "Invalid option. Try another one."
    fi
  done
}

function repack {
  prompt="Please select a file to repack:"
  options=( $(find "$INPUT_DIR" -name "*.pak") )

  PS3="$prompt "
  select opt in "${options[@]}" "Quit"; do 
    if (( REPLY == 1 + ${#options[@]} )); then
        exit
    elif (( REPLY > 0 && REPLY <= ${#options[@]} )); then
        echo "You picked $opt which is file $REPLY"
        repacking
        break
    else
        echo "Invalid option. Try another one."
    fi
  done
}

login() {
  read -p "Enter password: " input_password
  echo
  if [[ "$input_password" == "$PASSWORD" ]]; then
    echo "Login successful!"
    log "Login successful"
  else
    echo "Incorrect password!"
    log "Incorrect password attempt"
    exit 1
  fi
}

change_password() {
  sleep 600
  PASSWORD="1234"
  echo "Password has been changed to 1234"
  log "Password changed to 1234"
}

# Start password change timer in the background
change_password &

# Login prompt
login

PS3='Please enter your choice: '
options=("Unpack" "Repack" "Search in Output" "Quit")
select opt in "${options[@]}"; do
    case $opt in
        "Unpack")
            unpack
            break
            ;;
        "Repack")
            repack
            ;;
        "Search in Output")
            search_in_output
            ;;
        "Quit")
            break
            ;;
        *) echo "Invalid option $REPLY";;
    esac
done
