#!/bin/bash

# Coloring
NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'
BOLD='\033[1m'

# Banner Animation
clear
echo -e "${BOLD}${RED}🌸ꗥ～ꗥ🌸 𝐏𝐔𝐁𝐆-𝐏𝐀𝐒𝐓𝐄𝐑 🌸ꗥ～ꗥ🌸${NOCOLOR}"
sleep 0.5
echo -e "          ${BLUE}by ĐⱤ₳J ${NOCOLOR}"
sleep 0.5
echo -e "-----------------------"
sleep 0.5
echo -e "${GREEN}Join our Telegram channel for updates: ${CYAN}https://t.me/+6dw6gTPZu0FiOGRl${NOCOLOR}"
sleep 0.5

# Loading Animation
echo -ne "${YELLOW}Loading"
for i in {1..5}; do
    echo -ne "."
    sleep 0.5
done
echo -e "${NOCOLOR}"
